//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class kolcsonzesek
    {
        public int ID { get; set; }
        public Nullable<int> ki { get; set; }
        public Nullable<int> mit { get; set; }
        public Nullable<System.DateTime> ki_datum { get; set; }
        public Nullable<System.DateTime> vissza_datum { get; set; }
    }
}
